language: node_js
node_js:
- node
cache: npm
before_install: cd app
script: npm run test
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: production
env:
  global:
  - secure: ILfHLm2B9aTxdP3FGy9p/OCPK45tgKcGh5b6iNMn/h1OXZZk9bQzWiiJokFseQp00+tkbSkS4z+c3Lwx19DI5ozIMYHiWuCGJ27GJfejSM89a+fcyeP38eV6OyWcfH0eXCY/h+ArPykujHinM31hLW4AJYdWh5fpyXNIkP/UcplxT8GB1psCVcJefoiqqs8w0V6nNWpwY295Hgc7m/7mpT6wv6SiAi7YBDVO5xqyMdeiSVHrf5Dq9u4P1AkXkxeMS0G0pDWSnuUzHZ48K0GCU0lDJ8k8vTHUWzAiOnHVhiFB/V0wi1TUEKeV08+i/Xi7Xf3CDC6P25LoNBLaSFieJve5EbZ7x97i96PoojCsJ9vGf7GCLaObx/nvPX5x5AhNnVR8YMccy4et8ZZsYe96SJ3AZRpxh32ECiZzUCFOnvjqFMaJBd1Ql+BE4iy9m+9pogtDakdUlKShlQ/R/wMJx87in95CbVnbMweJOVxMATGD8ioapbDz5i5zkeBbrpfzaJJxUDGryRZ8mE8nE0DBuprjP3lPTwY/Di5cqVWkAPokDDIYE2wyCKuHz3I04luF9KCjjN2/tf3gnhyTUHjv7PveDttOC10NatkMQtHpNtcDXfV/OeezlHWpZI8ihWVyg9ljTXhAb7usZMNBlGkX4EtlBTydz06gSa0wiBO7yR0=
  - secure: XLkzv3qihBBVVxZcOLtH1qrEqjVE8Q8F3Saf36vMZsTQ6+CuGXoz29ccosBHbRLO1gz+Px7FBhK8d8GOzGEwZwUTkACcmt9QwgYSD5tUIPOecrLVrlcJpAJ6YbXfAfIQFRk2pnhSd/BdWWQCF57BCTcMjW4bjLKFts0UK/YUbkwe8te9lsHSKotwPVpHDtsPmpzaBDoGl3sGgTRIAuAf0uAsvZejx8EZx6xD0QOQ1wstBwEJ8puzIPLfgsqFNX43CFO9/bq3C8uKnATL2ni6F/qb84w0FaqmIsOYXdWrJTY2dmPpRjMyQOKk9aLj5/RFTRLJdoxut2w39XzWxz2UKubUqDKHog68WhNDuwmUXS9K9BPfmW94UoSMxUgaSM7VpPu4uK+UQ0JoOrUqWglZF00oCOqcGAHpWhIgr+cXegWuSdlsjLxTbQBRjen2aLNCJsTIUW3oq1gIrQU/FaHKCzlB2bfP2q6QpbEBKW+MONIr1c272Ce4avT/VluDhHW73hkqw6ea/5UQ0KI3rW0zoFY8xv6e29gcHZVGibFOe8OLTwW0T4HQU5aBwa+tyRpyl1Gx4YXN+n+PwoGBuep9RYyUdjvACi0BT93T/q9wyLZkkEhRWKB/1XHe+lLIPOLAgTcCId4LZ//IxKpztKK77arhOg5wYE56PCgfHxJXWuY=
